service: subscription-service
package:
  version: 0.0.1-SNAPSHOT
  artifact: ./application/target/${self:service}-${self:package.version}-${self:provider}.jar
provider:
  name: aws
  runtime: java11
  region: us-east-2
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    APPLICATION_ENVIRONMENT: Dev
    CLOUD_REGION: US_East_2
functions:
  subscribe:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: subscription/subscribe
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: subscribeFunction
  unsubscribe:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: subscription/unsubscribe
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: unsubscribeFunction
  findAllSubscriptions:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: subscription/findall
          method: get
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: findAllSubscriptionFunction
  findBySubscriptionId:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: subscription/findBy
          method: get
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: findByFunction

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Subscription
        AttributeDefinitions:
          - AttributeName: emailId
            AttributeType: S
          - AttributeName: active
            AttributeType: B
        KeySchema:
          - AttributeName: emailId
            KeyType: HASH
          - AttributeName: active
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1